project:
  type: website
  output-dir: ../docs 

authors:
  - name: Alessio Arcara
    url: https://github.com/alessioarcara
    affiliations: University of Bologna
  - name: Francesco Baiocchi
    url: https://github.com/francescobaio
    affiliations: University of Bologna
  - name: Leonardo Petrilli
    url: https://github.com/leonardopetrilli
    affiliations: University of Bologna   
date: "2025-07-01"
    

format:
  revealjs:
    logo: resources/logo_unibo.png
    theme: [default, custom.scss]   
    embed-resources: false
    smaller: true
    slide-number: false
    incremental: false
    history: false
    chalkboard: false
    preview-links: auto
    highlight-style: github
    code-overflow: scroll
    code-line-numbers: false
    
resources:
  - custom.scss
  - resources/**                
