project_name: "soccerai"
seed: 42
use_temporal: True 
model:
  model_name: "gcrnn"
  dmid: 256
  dhid: 128

trainer:
  bs: 32 
  n_epochs: 20
  lr: 1e-4
  wd: 0.01
  eval_rate: 2
  gamma: 0.9

data:
  include_goal_features: True 
  include_ball_features: True 
  use_macro_roles: True 
  use_augmentations: False
  use_regression_imputing: False
  use_pca_on_roster_cols: False 
  mask_non_possession_shooting_stats: False 
  connection_mode: "bipartite"
  val_ratio: 0.2