project_name: "soccerai"
run_name: "gine"
seed: 42

model: 
  use_temporal: True

  neck:
    readout: "mean"
    dhid: 256

  head:
    n_layers: 2
    drop: 0.5

trainer:
  bs: 128 
  n_epochs: 10
  lr: 1e-4
  wd: 1e-4
  eval_rate: 5
  gamma: 0.9
  
data:
  include_goal_features: True 
  include_ball_features: True 
  use_macro_roles: True 
  use_augmentations: False 
  use_regression_imputing: False
  use_pca_on_roster_cols: False 
  mask_non_possession_shooting_stats: False 
  connection_mode: "bipartite"
  val_ratio: 0.1

collector:
  n_frames: 12         

pitch_grid:
  nrows: 3
  ncols: 4
  figheight: 12

metrics:
  thr: 0.5
  fbeta: 1.0