project_name: "soccerai"
seed: 42
use_temporal: False 

model:
  name: "gnn"
  backbone:
    name: 'gcn2'
    drop: 0.1
    dhid: 256
    dout: 128
    n_layers: 9
    norm: 'none'
    skip_stride: 1
  neck:
    readout: 'mean'
    dhid: 256
    k: 1
  head:
    drop: 0.5
    n_layers: 1
    dout: 1

trainer:
  bs: 64
  n_epochs: 75
  lr: 1e-4
  wd: 1e-4
  eval_rate: 2
  gamma: 0.9
  
data:
  include_goal_features: True 
  include_ball_features: True 
  use_macro_roles: True 
  use_augmentations: False 
  use_regression_imputing: False
  use_pca_on_roster_cols: False 
  mask_non_possession_shooting_stats: False 
  connection_mode: "bipartite"
  val_ratio: 0.1

collector:
  n_frames: 12         

pitch_grid:
  nrows: 3
  ncols: 4
  figheight: 12

metrics:
  thr: 0.5
  fbeta: 1.0