project_name: "soccerai"
seed: 42
use_temporal: True 

model:
  model_name: "gcrnn"
  dmid: 256
  dhid: 128
  p_drop: 0.2
  n_layers: 9
  backbone: 'gcn2'
  use_norm: False
  readout: 'sum'

trainer:
  bs: 128
  n_epochs: 75
  lr: 1e-4
  wd: 1e-4
  eval_rate: 2
  gamma: 0.9
  
data:
  include_goal_features: True 
  include_ball_features: True 
  use_macro_roles: True 
  use_augmentations: True 
  use_regression_imputing: False
  use_pca_on_roster_cols: False 
  mask_non_possession_shooting_stats: False 
  connection_mode: "bipartite"
  val_ratio: 0.1

collector:
  n_frames: 12         

pitch_grid:
  nrows: 3
  ncols: 4
  figheight: 12

metrics:
  thr: 0.5
  fbeta: 1.0