project_name: "soccerai"
seed: 42
bs: 32 
n_epochs: 10
lr: 1e-2
wd: 1e-4
eval_rate: 1
val_ratio: 0.2
dim: 1024
use_goal_features: True 
connection_mode: "bipartite"
gamma: 0.5
accumulation_steps: 512 