project_name: "soccerai"
run_name: "gine"
seed: 42

model: 
  use_temporal: True 
  use_cell_state: True 

  backbone:
    dout: 256
    drop: 0.0
    norm: "none"
    residual_sum_mode: "none"

  neck:
    rnn_type: 'gru'
    readout: "mean"
    rnn_din: 512
    rnn_dout: 512 
    glob_dout: 256 
    mode: "node"
    raw_features_proj: True
    proj_dout: 128

  head:
    n_layers: 2
    din: 512
    drop: 0.5

trainer:
  bs: 32 
  n_epochs: 50
  lr: 1e-4
  wd: 1e-2
  gamma: 0.9
  eval_rate: 1

  early_stopping_callback:
    patience: 5
    history_key: "val_loss"
    minimize: True

  model_saving_callback:
    history_key: "val_loss"
    minimize: True
  
  
data:
  include_goal_features: False 
  include_ball_features: True 
  use_macro_roles: True 
  use_augmentations: False 
  use_regression_imputing: False
  use_pca_on_roster_cols: False 
  mask_non_possession_shooting_stats: False 
  connection_mode: "bipartite"
  val_ratio: 0.1

collector:
  n_frames: 24        

pitch_grid:
  nrows: 6
  ncols: 4
  figheight: 12

metrics:
  thr: 0.5
  fbeta: 1.0