model:
  use_cell_state: True
  use_hierarchical: True

  backbone:
    dhid: 64
    dout: 256
    drop: 0
    norm: "none"
    type: "diffpool"
    n_layers: 2
    pooling_ratio: 0.25
    dhid_multiplier: 1
    residual_sum_mode: "none" 
    
  neck:
    mode: "graph"
    readout: "sum"
    rnn_din: 256
    rnn_dout: 256
    rnn_type: "lstm"
    glob_dout: 64

  head:
    din: 256
    drop: 0.2
    n_layers: 3


