model:

  backbone:
    type: "gatv2"
    drop: 0.2
    norm: "none"
    n_layers: 2
    residual_sum_mode: "none"
    num_heads: 8
    use_edge_attr: True
    edge_dropout: 0.5

  neck:
    rnn_type: 'lstm'
    readout: "sum"
    mode: "graph"


trainer:
  bs: 128 
  lr: 1e-5