model:

  backbone:
    type: "gcn2"
    n_layers: 9 
    drop: 0.2

  neck:
    rnn_type: 'lstm'
    readout: "sum"
    mode: "graph"

trainer:
  bs: 64
  lr: 1e-5
  
data:
  use_augmentations: False 




