model:
  backbone:
    type: "gcn2"
    n_layers: 9 
    drop: 0.2
    norm: "batch"
    residual_sum_mode: "last"
    plus: True
  neck:
    rnn_type: 'gru'
    node_dout: 128
    drop: 0.1
    raw_features_proj: False
