model:
  backbone: 
    type: "gine"
    n_layers: 3
    dout: 64
    norm: "none"
    drop: 0.1
    train_eps: True

  neck:
    mode: "graph"
    glob_dout: 64
    rnn_din: 256
    rnn_dout: 256
    readout: "sum"

  head:
    din: 256