model:
  backbone:
    type: "graphsage"
    n_layers: 2
    drop: 0.1
    residual_sum_mode: "none"
    l2_norm: True
    aggr_type: "max"

  neck:
    rnn_type: 'lstm'
    readout: "sum"
    mode: "graph"
