model:
  backbone: 
    type: "graphgps"
    n_layers: 2
    heads: 4
    dout: 64
    drop: 0.1
    attn_drop: 0.5
    norm: "none"
    residual_sum_mode: "every"

  neck:
    mode: "node"
    rnn_type: "gru"
    rnn_din: 512
    rnn_dout: 96 
    glob_dout: 32 

  head: 
    n_layers: 2
    din: 96 
    drop: 0.5
    
training:
  lr: 1e-5
  bs: 128