# This file was auto-generated by ezconfy. Do not edit manually.
from eztrain.callbacks import Callback
from eztrain.loggers import Logger
from eztrain.metrics import MetricCollection
from pydantic import BaseModel, ConfigDict, Field
from torch.nn.modules.module import Module
from torch.optim.lr_scheduler import LRScheduler
from torch.optim.optimizer import Optimizer
from torch.utils.data.dataloader import DataLoader

from soccerai.data.converters import GraphConverter
from soccerai.data.dataset import WorldCup2022Dataset
from soccerai.data.temporal_dataset import TemporalChainsDataset
from soccerai.training.trainer import BaseTrainer


class DataConfig(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    val_ratio: float = Field(...)
    split_mode: str = Field("chronological")
    drop_games_without_negatives: bool = Field(True)
    goal_window_for_positives: float | None = Field(None)
    include_goal_features: bool = Field(...)
    include_ball_features: bool = Field(...)
    use_macro_roles: bool = Field(...)
    use_augmentations: bool = Field(...)
    use_regression_imputing: bool = Field(...)
    use_pca_on_roster_cols: bool = Field(...)
    mask_non_possession_shooting_stats: bool = Field(...)
    normalize_attack_direction: bool = Field(True)
    max_chain_len: int | None = Field(None)
    use_roster_features: bool = Field(False)
    use_match_clock: bool = Field(False)


class ConfigModel(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    project_name: str = Field(...)
    run_name: str = Field(...)
    seed: int = Field(...)
    device: str = Field("auto")
    n_epochs: int = Field(...)
    batch_size: int = Field(...)
    num_workers: int = Field(...)
    lr: float = Field(...)
    max_lr: float = Field(...)
    wd: float = Field(...)
    eval_rate: int = Field(...)
    threshold: float = Field(...)
    fbeta: float = Field(...)
    collector_frames: int = Field(...)
    resume_from: str | None = Field(None)
    steps_per_epoch: int = Field(...)
    data_config: DataConfig = Field(...)
    converter: GraphConverter = Field(...)
    train_ds: WorldCup2022Dataset = Field(...)
    val_ds: WorldCup2022Dataset = Field(...)
    train_chains: TemporalChainsDataset = Field(...)
    val_chains: TemporalChainsDataset = Field(...)
    train_loader: DataLoader = Field(...)
    val_loader: DataLoader = Field(...)
    pos_weight: float | None = Field(None)
    backbone: Module = Field(...)
    neck: Module = Field(...)
    head: Module = Field(...)
    model: Module = Field(...)
    optim: Optimizer = Field(...)
    scheduler: LRScheduler = Field(...)
    metrics: MetricCollection = Field(...)
    callbacks: list[Callback] = Field(...)
    logger: Logger = Field(...)
    trainer: BaseTrainer = Field(...)
